language: scala
scala:
    - 2.12.11
jdk:
    - oraclejdk11
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_script:
  - ./get-z3-linux.sh
  - ls $PWD/z3/bin/
  - export PATH=$PATH:$PWD/z3/bin/
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/z3/bin/
script: sbt ++$TRAVIS_SCALA_VERSION test


